// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package gopher represents the world "better-together:gopher/gopher@0.1.0".
//
// A single Gopher player component: a WASI 0.2 reactor that exports the
// Better Together player interface.
package gopher
