// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "better-together:gardener/types@0.1.0".
//
// Shared value types used by both the player and the engine.
package types

import (
	"go.bytecodealliance.org/cm"
)

// PlayerID represents the string "better-together:gardener/types@0.1.0#player-id".
//
// A persistent, globally unique player identity (e.g. a component name).
//
//	type player-id = string
type PlayerID string

// Metadata represents the record "better-together:gardener/types@0.1.0#metadata".
//
// A player component's self-description: who wrote it and where it lives.
// Returned by `gardener.metadata` so the engine can build a registry /
// leaderboard without constructing or running the player.
//
//	record metadata {
//		name: string,
//		version: string,
//		author: string,
//		repo: string,
//		lore: string,
//	}
type Metadata struct {
	_ cm.HostLayout `json:"-"`
	// Human-readable name of this player (often used as the player-id).
	Name string `json:"name"`

	// Semantic version of this player, e.g. "1.0.0".
	Version string `json:"version"`

	// Author or team that wrote this player.
	Author string `json:"author"`

	// Project / source repository URL.
	Repo string `json:"repo"`

	// A short, in-character backstory for this gardener. Flavor only — the
	// engine never parses it; it exists so leaderboards and match logs can
	// show who this bot *is*.
	Lore string `json:"lore"`
}

// Signal represents the enum "better-together:gardener/types@0.1.0#signal".
//
// The public broadcast a player emits each round. Cheap talk — it carries
// no enforced meaning and may be honest or deceptive.
//
//	enum signal {
//		bloom,
//		hold,
//		watch
//	}
type Signal uint8

const (
	// "I intend to plant generously this round."
	SignalBloom Signal = iota

	// "I intend to keep most/all of my seeds."
	SignalHold

	// "I'm deciding based on what others do."
	SignalWatch
)

var _SignalStrings = [3]string{
	"bloom",
	"hold",
	"watch",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Signal) String() string {
	return _SignalStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Signal) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Signal) UnmarshalText(text []byte) error {
	return _SignalUnmarshalCase(e, text)
}

var _SignalUnmarshalCase = cm.CaseUnmarshaler[Signal](_SignalStrings[:])

// PlayerAction represents the record "better-together:gardener/types@0.1.0#player-action".
//
// What a single player did in a given round, revealed to everyone.
//
//	record player-action {
//		id: player-id,
//		plant: u8,
//		signal: signal,
//	}
type PlayerAction struct {
	_  cm.HostLayout `json:"-"`
	ID PlayerID      `json:"id"`

	// Seeds placed in the shared garden this round, 0-10.
	Plant  uint8  `json:"plant"`
	Signal Signal `json:"signal"`
}

// RoundResult represents the record "better-together:gardener/types@0.1.0#round-result".
//
// The fully resolved outcome of one round, broadcast to all players.
//
//	record round-result {
//		actions: list<player-action>,
//		garden-total: u16,
//		multiplier: f32,
//		garden-payout: f32,
//	}
type RoundResult struct {
	_ cm.HostLayout `json:"-"`
	// One entry per player in the match.
	Actions cm.List[PlayerAction] `json:"actions"`

	// Sum of every player's `plant` this round.
	GardenTotal uint16 `json:"garden-total"`

	// Diversity multiplier: 1.0 + 0.5 * distinct-contributors.
	Multiplier float32 `json:"multiplier"`

	// (garden-total * multiplier) / group-size, paid to every player.
	GardenPayout float32 `json:"garden-payout"`
}

// MatchContext represents the record "better-together:gardener/types@0.1.0#match-context".
//
// Delivered once at the start of a match, before any rounds.
//
//	record match-context {
//		match-id: string,
//		players: list<player-id>,
//		self-id: player-id,
//		group-size: u8,
//	}
type MatchContext struct {
	_ cm.HostLayout `json:"-"`
	// Identifier for this match.
	MatchID string `json:"match-id"`

	// Every player in this match, including yourself.
	Players cm.List[PlayerID] `json:"players"`

	// Your own identity within `players`.
	SelfID PlayerID `json:"self-id"`

	// Group size K (4-6). The number of rounds R is intentionally hidden.
	GroupSize uint8 `json:"group-size"`
}

// SignalBroadcast represents the record "better-together:gardener/types@0.1.0#signal-broadcast".
//
// One player's broadcast for the CURRENT round, revealed to everyone during
// the talk phase before anyone plants.
//
//	record signal-broadcast {
//		id: player-id,
//		signal: signal,
//	}
type SignalBroadcast struct {
	_      cm.HostLayout `json:"-"`
	ID     PlayerID      `json:"id"`
	Signal Signal        `json:"signal"`
}

// RoundState represents the record "better-together:gardener/types@0.1.0#round-state".
//
// Delivered to both `talk` and `plant` each round. The number of remaining
// rounds is never revealed.
//
//	record round-state {
//		round: u8,
//		history: list<round-result>,
//		signals: list<signal-broadcast>,
//	}
type RoundState struct {
	_ cm.HostLayout `json:"-"`
	// 1-based index of the round you are about to play.
	Round uint8 `json:"round"`

	// Every previous round of this match, oldest first.
	History cm.List[RoundResult] `json:"history"`

	// This round's broadcasts. Empty when passed to `talk` (no one has
	// spoken yet); when passed to `plant` it holds the signal every player
	// — including you — broadcast this round, so plants can react to talk.
	Signals cm.List[SignalBroadcast] `json:"signals"`
}

// MatchSummary represents the record "better-together:gardener/types@0.1.0#match-summary".
//
// Delivered once when the match ends.
//
//	record match-summary {
//		rounds-played: u8,
//		final-scores: list<tuple<player-id, f32>>,
//		your-score: f32,
//	}
type MatchSummary struct {
	_ cm.HostLayout `json:"-"`
	// How many rounds the match actually ran (R, 8-12).
	RoundsPlayed uint8 `json:"rounds-played"`

	// Final match score for every player.
	FinalScores cm.List[cm.Tuple[PlayerID, float32]] `json:"final-scores"`

	// Your own final match score.
	YourScore float32 `json:"your-score"`
}
