// User-owned class definition for Keith's exported `gardener` resource.
//
// `wit-bindgen cpp` generates this file ONCE (as a stub) and thereafter writes
// refreshed copies to `*.template` instead of overwriting it — so it is checked
// into the repository as hand-owned source and the build regenerates only the
// glue (`keith.cpp`, `keith_cpp.h`, `wit.h`, `keith_component_type.o`) around it.
//
// Two deliberate edits on top of the generator's stub:
//   1. Forward declarations of the `better_together::gardener::types` namespace,
//      because `keith_cpp.h` includes THIS header before it defines those types;
//      without the forward decls the member signatures below fail to name them.
//   2. Keith's per-seat state (identity, this-match observations, and the
//      cross-match debt ledger loaded from / saved to the virtual filesystem).
#pragma once
#include <cstdint>
#include <utility>
#include <expected>
#include <map>
#include <string>
#include <tuple>
#include <vector>
#include "wit.h"

// (1) Forward declarations — the full definitions live in keith_cpp.h, which
// includes this header first. Member declarations may name incomplete types;
// the definitions (in keith.cpp) and this class's method bodies see the
// complete types via keith_cpp.h.
namespace better_together {
  namespace gardener {
    namespace types {
      struct Metadata;
      enum class Signal : uint8_t;
      struct MatchContext;
      struct RoundState;
      struct MatchSummary;
    }
  }
}

/* User class definition file, autogenerated once, then user modified
* Updated versions of this file are generated into Gardener.template.
*/
namespace exports {
  namespace better_together {
    namespace gardener {
      namespace player {
        class Gardener : public wit::ResourceExportBase<Gardener>{

          public:

          // (2) Keith's per-seat state. All internal bookkeeping uses std:: types;
          // only the WIT boundary (method signatures below) speaks wit::.

          /// One opponent's observed conduct. `blooms`/`lies` track promises:
          /// a "lie" is a round where they signalled BLOOM but planted < 3
          /// (a visibly broken promise — the bite the rat remembers).
          struct Rep {
            uint32_t rounds = 0;    // rounds we have seen this opponent act
            uint32_t contribs = 0;  // rounds they planted >= 3 (a contributor)
            uint32_t blooms = 0;    // rounds they signalled BLOOM
            uint32_t lies = 0;      // BLOOM signalled but planted < 3
          };

          std::string self_id;                  // our identity this match
          std::vector<std::string> opponents;   // everyone else at the table
          std::map<std::string, Rep> lifetime;  // cross-match ledger (loaded at match start)
          std::map<std::string, Rep> match_obs;  // this match only (recomputed each round)
          std::string mem_path;                  // ledger file on the virtual filesystem

          uint8_t planned_plant = 0;  // generosity chosen in `talk`, honoured in `plant`
          uint8_t planned_round = 0;  // the round `planned_plant` was decided for

          static void Dtor(player::Gardener* self){delete self;}
          /// Describe this player: name, version, author, repository URL, and lore.
          std::expected<::better_together::gardener::types::Metadata, wit::Void> Metadata();
          /// Begin a new match.
          std::expected<void, wit::Void> MatchStart(::better_together::gardener::types::MatchContext context);
          /// Talk phase: broadcast this round's signal BEFORE anyone plants.
          /// `state.signals` is empty here. Cheap talk — it may be honest or a
          /// lie. Must respect the 10 ms / 16 MB budget.
          std::expected<::better_together::gardener::types::Signal, wit::Void> Talk(::better_together::gardener::types::RoundState state);
          /// Plant phase: decide how many of your 10 seeds to plant, 0-10 (the
          /// engine clamps out-of-range values). `state.signals` now holds every
          /// player's talk from this round, so you can react to what was promised.
          /// Must respect the 10 ms / 16 MB budget.
          std::expected<uint8_t, wit::Void> Plant(::better_together::gardener::types::RoundState state);
          /// The match has ended. Persist any updated memory to the virtual
          /// filesystem here (there is no return blob).
          std::expected<void, wit::Void> MatchEnd(::better_together::gardener::types::MatchSummary summary);
          static int32_t ResourceNew(player::Gardener* self);
          static Gardener* ResourceRep(int32_t id);
          static void ResourceDrop(int32_t id);
        };

      }
    }
  }
}
