// Code generated by wit-bindgen-go. DO NOT EDIT.

package player

import (
	"github.com/pavelsavara/better-together/samples/gopher/internal/better-together/gardener/types"
	"go.bytecodealliance.org/cm"
)

func lift_MatchSummary(f0 uint32, f1 *cm.Tuple[types.PlayerID, float32], f2 uint32, f3 float32) (v types.MatchSummary) {
	v.RoundsPlayed = (uint8)(f0)
	v.FinalScores = cm.LiftList[cm.List[cm.Tuple[types.PlayerID, float32]]](f1, f2)
	v.YourScore = (float32)(f3)
	return
}

func lift_MatchContext(f0 *uint8, f1 uint32, f2 *types.PlayerID, f3 uint32, f4 *uint8, f5 uint32, f6 uint32) (v types.MatchContext) {
	v.MatchID = cm.LiftString[string](f0, f1)
	v.Players = cm.LiftList[cm.List[types.PlayerID]](f2, f3)
	v.SelfID = cm.LiftString[types.PlayerID](f4, f5)
	v.GroupSize = (uint8)(f6)
	return
}

func lift_RoundState(f0 uint32, f1 *types.RoundResult, f2 uint32, f3 *types.SignalBroadcast, f4 uint32, f5 *types.PlayerAction, f6 uint32) (v types.RoundState) {
	v.Round = (uint8)(f0)
	v.History = cm.LiftList[cm.List[types.RoundResult]](f1, f2)
	v.Signals = cm.LiftList[cm.List[types.SignalBroadcast]](f3, f4)
	v.Plants = cm.LiftList[cm.List[types.PlayerAction]](f5, f6)
	return
}
