// Code generated by wit-bindgen-go. DO NOT EDIT.

package player

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "better-together:gardener/player@0.1.0".
var Exports struct {
	// Gardener represents the caller-defined exports for resource "better-together:gardener/player@0.1.0#gardener".
	Gardener struct {
		// Destructor represents the caller-defined, exported destructor for resource "gardener".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// MatchEnd represents the caller-defined, exported method "match-end".
		//
		// The match has ended. Persist any updated memory to the virtual
		// filesystem here (there is no return blob).
		//
		//	match-end: func(summary: match-summary) -> result
		MatchEnd func(self cm.Rep, summary MatchSummary) (result cm.BoolResult)

		// MatchStart represents the caller-defined, exported method "match-start".
		//
		// Begin a new match.
		//
		//	match-start: func(context: match-context) -> result
		MatchStart func(self cm.Rep, context MatchContext) (result cm.BoolResult)

		// Metadata represents the caller-defined, exported method "metadata".
		//
		// Describe this player: name, version, author, repository URL, and lore.
		//
		//	metadata: func() -> result<metadata>
		Metadata func(self cm.Rep) (result cm.Result[Metadata, Metadata, struct{}])

		// Plant represents the caller-defined, exported method "plant".
		//
		// Plant phase: decide how many of your 10 seeds to plant, 0-10 (the
		// engine clamps out-of-range values). `state.signals` now holds every
		// player's talk from this round, so you can react to what was promised.
		// Must respect the 10 ms / 16 MB budget.
		//
		//	plant: func(state: round-state) -> result<u8>
		Plant func(self cm.Rep, state RoundState) (result cm.Result[uint8, uint8, struct{}])

		// Talk represents the caller-defined, exported method "talk".
		//
		// Talk phase: broadcast this round's signal BEFORE anyone plants.
		// `state.signals` is empty here. Cheap talk — it may be honest or a
		// lie. Must respect the 10 ms / 16 MB budget.
		//
		//	talk: func(state: round-state) -> result<signal>
		Talk func(self cm.Rep, state RoundState) (result cm.Result[Signal, Signal, struct{}])
	}

	// Create represents the caller-defined, exported function "create".
	//
	// Static factory: create a new player instance. The router host calls this
	// once per seat to spin up a gardener, which loads any persisted memory
	// from the virtual filesystem and prepares to play.
	//
	//	create: func() -> result<gardener>
	Create func() (result cm.Result[Gardener, Gardener, struct{}])
}
