// Code generated by wit-bindgen-go. DO NOT EDIT.

package player

import (
	"github.com/pavelsavara/better-together/samples/gopher/internal/better-together/gardener/types"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "better-together:gardener@0.1.0".

//go:wasmimport [export]better-together:gardener/player@0.1.0 [resource-new]gardener
//go:noescape
func wasmimport_GardenerResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]better-together:gardener/player@0.1.0 [resource-rep]gardener
//go:noescape
func wasmimport_GardenerResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]better-together:gardener/player@0.1.0 [resource-drop]gardener
//go:noescape
func wasmimport_GardenerResourceDrop(self0 uint32)

//go:wasmexport better-together:gardener/player@0.1.0#[dtor]gardener
//export better-together:gardener/player@0.1.0#[dtor]gardener
func wasmexport_GardenerDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Gardener.Destructor(self)
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#[method]gardener.match-end
//export better-together:gardener/player@0.1.0#[method]gardener.match-end
func wasmexport_GardenerMatchEnd(self0 uint32, summary0 uint32, summary1 *cm.Tuple[types.PlayerID, float32], summary2 uint32, summary3 float32) (result0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	summary := lift_MatchSummary((uint32)(summary0), (*cm.Tuple[types.PlayerID, float32])(summary1), (uint32)(summary2), (float32)(summary3))
	result := Exports.Gardener.MatchEnd(self, summary)
	result0 = (uint32)(result)
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#[method]gardener.match-start
//export better-together:gardener/player@0.1.0#[method]gardener.match-start
func wasmexport_GardenerMatchStart(self0 uint32, context0 *uint8, context1 uint32, context2 *types.PlayerID, context3 uint32, context4 *uint8, context5 uint32, context6 uint32) (result0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	context := lift_MatchContext((*uint8)(context0), (uint32)(context1), (*types.PlayerID)(context2), (uint32)(context3), (*uint8)(context4), (uint32)(context5), (uint32)(context6))
	result := Exports.Gardener.MatchStart(self, context)
	result0 = (uint32)(result)
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#[method]gardener.metadata
//export better-together:gardener/player@0.1.0#[method]gardener.metadata
func wasmexport_GardenerMetadata(self0 uint32) (result *cm.Result[Metadata, Metadata, struct{}]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Gardener.Metadata(self)
	result = &result_
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#[method]gardener.plant
//export better-together:gardener/player@0.1.0#[method]gardener.plant
func wasmexport_GardenerPlant(self0 uint32, state0 uint32, state1 *types.RoundResult, state2 uint32, state3 *types.SignalBroadcast, state4 uint32) (result *cm.Result[uint8, uint8, struct{}]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	state := lift_RoundState((uint32)(state0), (*types.RoundResult)(state1), (uint32)(state2), (*types.SignalBroadcast)(state3), (uint32)(state4))
	result_ := Exports.Gardener.Plant(self, state)
	result = &result_
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#[method]gardener.talk
//export better-together:gardener/player@0.1.0#[method]gardener.talk
func wasmexport_GardenerTalk(self0 uint32, state0 uint32, state1 *types.RoundResult, state2 uint32, state3 *types.SignalBroadcast, state4 uint32) (result *cm.Result[Signal, Signal, struct{}]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	state := lift_RoundState((uint32)(state0), (*types.RoundResult)(state1), (uint32)(state2), (*types.SignalBroadcast)(state3), (uint32)(state4))
	result_ := Exports.Gardener.Talk(self, state)
	result = &result_
	return
}

//go:wasmexport better-together:gardener/player@0.1.0#create
//export better-together:gardener/player@0.1.0#create
func wasmexport_Create() (result *cm.Result[Gardener, Gardener, struct{}]) {
	result_ := Exports.Create()
	result = &result_
	return
}
