// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package player represents the exported interface "better-together:gardener/player@0.1.0".
//
// The contract every player component implements. The router host constructs
// one `gardener` per seat, then drives it in order across a match: match-start,
// then `talk` + `plant` per round, then match-end.
package player

import (
	"github.com/pavelsavara/better-together/samples/gopher/internal/better-together/gardener/types"
	"go.bytecodealliance.org/cm"
)

// Metadata represents the type alias "better-together:gardener/player@0.1.0#metadata".
//
// See [types.Metadata] for more information.
type Metadata = types.Metadata

// Signal represents the type alias "better-together:gardener/player@0.1.0#signal".
//
// See [types.Signal] for more information.
type Signal = types.Signal

// MatchContext represents the type alias "better-together:gardener/player@0.1.0#match-context".
//
// See [types.MatchContext] for more information.
type MatchContext = types.MatchContext

// RoundState represents the type alias "better-together:gardener/player@0.1.0#round-state".
//
// See [types.RoundState] for more information.
type RoundState = types.RoundState

// MatchSummary represents the type alias "better-together:gardener/player@0.1.0#match-summary".
//
// See [types.MatchSummary] for more information.
type MatchSummary = types.MatchSummary

// Gardener represents the exported resource "better-together:gardener/player@0.1.0#gardener".
//
// A single seated player. The router host creates one of these per
// gardener component and forwards the engine's calls to it.
//
//	resource gardener
type Gardener cm.Resource

// GardenerResourceNew represents the imported resource-new for resource "gardener".
//
// Creates a new resource handle.
//
//go:nosplit
func GardenerResourceNew(rep cm.Rep) (result Gardener) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_GardenerResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Gardener]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "gardener".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Gardener) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_GardenerResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "gardener".
//
// Drops a resource handle.
//
//go:nosplit
func (self Gardener) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_GardenerResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Gardener.Destructor = func(self cm.Rep) {}
}
